name: main-ci

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

env:
  RUFF_VERSION: "0.13.3"
  TAPLO_VERSION: "0.9.3"

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-alpine
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install --no-cache-dir ruff==${{ env.RUFF_VERSION }}
          pip install -r ./requirements/base.txt
          ruff check .

  taplo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Taplo
        run: |
          curl -fsSL https://github.com/tamasfe/taplo/releases/download/${{ env.TAPLO_VERSION }}/taplo-linux-x86_64.gz | gunzip -c - | install -m 755 /dev/stdin /usr/local/bin/taplo
      - name: Run Taplo
        run: taplo format --check --diff

  build:
    runs-on: ubuntu-latest
    needs: [lint, taplo]
    container:
      image: python:3.12-alpine
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install --no-cache-dir build
          python -m build --sdist --wheel --outdir dist
